CREATE DATABASE IF NOT EXISTS health;
USE health;

DROP TABLE IF EXISTS foods;
DROP TABLE IF EXISTS users;

CREATE USER IF NOT EXISTS 'gold'@'localhost'
IDENTIFIED BY 'qwertyuiop';

GRANT ALL PRIVILEGES ON health.* TO 'gold'@'localhost';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS foods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  calories INT DEFAULT 0,
  protein FLOAT DEFAULT 0,
  carbs FLOAT DEFAULT 0,
  fats FLOAT DEFAULT 0
);
